services:
  backend:
    image: sasharevenko/hacker-news-backend
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - HOST=localhost
      - API_URL=https://api.hnpwa.com/v0/

  frontend:
    image: sasharevenko/hacker-news-frontend
    ports:
      - 3000:80
    environment:
      - VITE_BACKEND_URL='http://localhost:4000'
